### ISSUE TITLE
support SPARQL endpoints in addition to loading from turtle files?

### ISSUE THREAD

**Issue by KonradHoeffner** [KonradHoeffner/rickview#13]
@Aklakan requests SPARQL endpoint support. As this would be a major addition and contrary to the initial direction, investigate how much effort this would take and what the performance would be.

**Comment by pchampin** [comment]
btw, very nice project, and thanks for chosing Sophia to implement it :-)

You might want to look at https://github.com/pchampin/sophia_sparql_client .
I hacked it quickly as a poof of concept, but this should do the trick.

PS: ultimately, I would like to include a generic SPARQL engine in Sophia, so that any [Dataset](https://docs.rs/sophia/latest/sophia/dataset/trait.Dataset.html) (even in-memory ones) could be wrapped into a [SparqlDataset](https://docs.rs/sophia/latest/sophia/sparql/trait.SparqlDataset.html). But that's not a small task...

**Comment by KonradHoeffner** [comment]
@pchampin: Thanks! Sophia fits very well for this project because [triples_with_s](https://docs.rs/sophia/latest/sophia/graph/trait.Graph.html#method.triples_with_s) and triples_with_o are key for an RDF browser and sophia is optimized for that. So I'm not sure if I would change that to a SPARQL query and risk a performance overhead. I think I would rather have it as an alternative code path for people who do want to use RickView with a SPARQL endpoint but optimize RickView further for in-memory graphs using HDT, which also supports fast triples_with_s and triples_with_o queries but no SPARQL.

**Comment by KonradHoeffner** [comment]
Not planning to implement this right now, may reopen it later.
