### ISSUE TITLE
Update footer link to "create issue about the knowledge base on GitHub"

### ISSUE THREAD

**Issue by ChristophB** [KonradHoeffner/rickview#73]
![image](https://github.com/KonradHoeffner/rickview/assets/1651973/7f25bb74-43ce-4e31-b5df-9b248c3f2741)

The text of the link suggests that it is to the new issues form of the knowledgebase, but it only points to the repository home page.

## Example
https://www.snik.eu/ontology/ob/3LGM2ApplicationComponent

Footer entries are:

1. "create issue about this resource on GitHub" -> https://github.com/snikproject/ontology/issues/new?title=3LGM2ApplicationComponent
2. "create issue about the knowledge base on GitHub" -> https://github.com/snikproject/ontology

## Expected behaviour
2. should link to https://github.com/snikproject/ontology/issues/new

**or**

2. link text should be "view the knowledge base on GitHub"

**Comment by KonradHoeffner** [comment]
You are right that this is misleading, however I do not prefer to link to `issues/new` because this could lead to users not seeing that an issue about their problem already exists and then there would be duplicates.
The other footer entry has the same problem however I think there it is less of a risk of duplication because it concerns a single issue and the benefit of automatically populating the issue title outweighs this.
@ChristophB: So maybe "view the knowledge base on GitHub" would actually be best or link to ".../issues" and call it "view issues about the knowledge base on GitHub", what do you think?

**Comment by ChristophB** [comment]
> link to ".../issues" and call it "view issues about the knowledge base on GitHub"

I like this one.
